# Generated by Django 3.1.3 on 2020-11-23 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getstatus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='title',
            field=models.CharField(default='Incident', max_length=200),
            preserve_default=False,
        ),
    ]
