# Generated by Django 3.1.3 on 2020-11-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getstatus', '0002_incident_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='description',
            field=models.CharField(default='-', max_length=500),
            preserve_default=False,
        ),
    ]
